name: covid19india
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.11

  grizzly_scales: ^2.0.2

  autotrie: ^0.4.1

  hive: ^1.4.1

  path_provider: ^1.6.11

  path_drawing: ^0.4.1

  fl_chart: ^0.10.0

  intl: ^0.16.1

  get_it: ^4.0.2

  flutter_bloc: ^4.0.1

  dartz: ^0.9.1

  equatable: ^1.2.0

  data_connection_checker: ^0.3.4

  shared_preferences: ^0.5.7

  http: ^0.12.1

  cupertino_icons: ^0.1.3

  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

  hive_generator: ^0.5.2

  build_runner: ^1.10.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
