import 'package:covid19india/core/entity/map_codes.dart';
import 'package:covid19india/core/entity/statistic.dart';
import 'package:flutter/material.dart';

const List<Statistic> PRIMARY_STATISTICS = <Statistic>[
  Statistic.confirmed,
  Statistic.active,
  Statistic.recovered,
  Statistic.deceased
];

const List<Statistic> TABLE_STATISTICS = [
  ...PRIMARY_STATISTICS,
  Statistic.tested
];

const List<Statistic> MAP_STATISTICS = [
  ...PRIMARY_STATISTICS,
  Statistic.tested
];

const List<Statistic> TIME_SERIES_STATISTICS = [
  ...PRIMARY_STATISTICS,
  Statistic.tested
];

const int MINIGRAPH_LOOKBACK_DAYS = 20;

const int CACHE_TIMEOUT_IN_MINUTES = 15;

const int DISTRICT_TABLE_COUNT = 30;

const Map<Statistic, Color> STATS_COLOR = {
  Statistic.confirmed: Colors.red,
  Statistic.active: Colors.blue,
  Statistic.recovered: Colors.green,
  Statistic.deceased: Colors.grey,
  Statistic.tested: Colors.purple,
  Statistic.migrated: Colors.yellow,
};

const Map<Statistic, List<Color>> STATS_GRADIENT_COLOR = {
  Statistic.confirmed: <Color>[Color(0xFFEF9A9A), Color(0xFFB71C1C)],
  Statistic.active: <Color>[Color(0xFF90CAF9), Color(0xFF0D47A1)],
  Statistic.recovered: <Color>[Color(0xFFA5D6A7), Color(0xFF1B5E20)],
  Statistic.deceased: <Color>[Color(0xFFEEEEEE), Color(0xFF212121)],
  Statistic.tested: <Color>[Color(0xFFCE93D8), Color(0xFF4A148C)],
  Statistic.migrated: <Color>[Color(0xFFFFF59D), Color(0xFFF57F17)],
};

const Map<Statistic, Color> STATS_HIGHLIGHT_COLOR = {
  Statistic.confirmed: Colors.redAccent,
  Statistic.active: Colors.blueAccent,
  Statistic.recovered: Colors.greenAccent,
  Statistic.deceased: Colors.blueGrey,
  Statistic.tested: Colors.purpleAccent,
  Statistic.migrated: Colors.orangeAccent,
};

const UNASSIGNED_STATE_CODE = 'UN';

const UNKNOWN_DISTRICT_KEY = 'Unknown';

const Map<MapCodes, List<String>> STATE_DISTRICT_MAP = {
  MapCodes.DN: ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
  MapCodes.DL: [
    'North Delhi',
    'New Delhi',
    'East Delhi',
    'North West Delhi',
    'West Delhi',
    'South Delhi',
    'Central Delhi',
    'Shahdara',
    'South West Delhi',
    'South East Delhi',
    'North East Delhi'
  ],
  MapCodes.WB: [
    'Hooghly',
    'Purba Medinipur',
    'South 24 Parganas',
    'Nadia',
    'Kolkata',
    'Dakshin Dinajpur',
    'Purulia',
    'Howrah',
    'Alipurduar',
    'Paschim Medinipur',
    'Paschim Bardhaman',
    'Jalpaiguri',
    'Uttar Dinajpur',
    'Jhargram',
    'Kalimpong',
    'Bankura',
    'Purba Bardhaman',
    'Birbhum',
    'North 24 Parganas',
    'Darjeeling',
    'Cooch Behar',
    'Malda',
    'Murshidabad'
  ],
  MapCodes.HR: [
    'Jind',
    'Jhajjar',
    'Rohtak',
    'Mahendragarh',
    'Ambala',
    'Kaithal',
    'Faridabad',
    'Karnal',
    'Kurukshetra',
    'Palwal',
    'Hisar',
    'Panchkula',
    'Gurugram',
    'Charkhi Dadri',
    'Panipat',
    'Fatehabad',
    'Rewari',
    'Bhiwani',
    'Nuh',
    'Sirsa',
    'Yamunanagar',
    'Sonipat'
  ],
  MapCodes.HP: [
    'Hamirpur',
    'Kullu',
    'Lahaul and Spiti',
    'Shimla',
    'Solan',
    'Chamba',
    'Una',
    'Bilaspur',
    'Kangra',
    'Kinnaur',
    'Mandi',
    'Sirmaur'
  ],
  MapCodes.MH: [
    'Satara',
    'Mumbai Suburban',
    'Beed',
    'Solapur',
    'Washim',
    'Thane',
    'Sindhudurg',
    'Wardha',
    'Dhule',
    'Buldhana',
    'Mumbai',
    'Chandrapur',
    'Amravati',
    'Aurangabad',
    'Raigad',
    'Hingoli',
    'Ratnagiri',
    'Jalgaon',
    'Pune',
    'Nandurbar',
    'Gadchiroli',
    'Nagpur',
    'Ahmednagar',
    'Sangli',
    'Nanded',
    'Kolhapur',
    'Bhandara',
    'Akola',
    'Osmanabad',
    'Gondia',
    'Parbhani',
    'Palghar',
    'Jalna',
    'Nashik',
    'Yavatmal',
    'Latur'
  ],
  MapCodes.JH: [
    'Pakur',
    'Ranchi',
    'Godda',
    'Chatra',
    'Simdega',
    'Khunti',
    'Bokaro',
    'Deoghar',
    'West Singhbhum',
    'Jamtara',
    'East Singhbhum',
    'Ramgarh',
    'Sahibganj',
    'Gumla',
    'Saraikela-Kharsawan',
    'Dumka',
    'Garhwa',
    'Latehar',
    'Giridih',
    'Hazaribagh',
    'Lohardaga',
    'Koderma',
    'Palamu',
    'Dhanbad'
  ],
  MapCodes.BR: [
    'Saran',
    'Samastipur',
    'Munger',
    'Lakhisarai',
    'Gopalganj',
    'Patna',
    'Rohtas',
    'Madhepura',
    'Jehanabad',
    'Muzaffarpur',
    'Sheohar',
    'Araria',
    'Aurangabad',
    'Buxar',
    'West Champaran',
    'East Champaran',
    'Katihar',
    'Sheikhpura',
    'Gaya',
    'Nawada',
    'Purnia',
    'Madhubani',
    'Saharsa',
    'Begusarai',
    'Supaul',
    'Banka',
    'Arwal',
    'Sitamarhi',
    'Kaimur',
    'Darbhanga',
    'Nalanda',
    'Vaishali',
    'Khagaria',
    'Jamui',
    'Bhojpur',
    'Bhagalpur',
    'Kishanganj',
    'Siwan'
  ],
  MapCodes.JK: [
    'Samba',
    'Kulgam',
    'Kupwara',
    'Anantnag',
    'Reasi',
    'Muzaffarabad',
    'Mirpur',
    'Jammu',
    'Punch',
    'Shopiyan',
    'Srinagar',
    'Ganderbal',
    'Doda',
    'Bandipora',
    'Baramulla',
    'Rajouri',
    'Udhampur',
    'Budgam',
    'Kathua',
    'Ramban',
    'Pulwama',
    'Kishtwar'
  ],
  MapCodes.PB: [
    'Sangrur',
    'Sri Muktsar Sahib',
    'Amritsar',
    'Jalandhar',
    'Moga',
    'Bathinda',
    'Ludhiana',
    'Ferozepur',
    'Gurdaspur',
    'Barnala',
    'Rupnagar',
    'Faridkot',
    'Fatehgarh Sahib',
    'Hoshiarpur',
    'Pathankot',
    'Patiala',
    'Fazilka',
    'Mansa',
    'Shahid Bhagat Singh Nagar',
    'Kapurthala',
    'Tarn Taran',
    'S.A.S. Nagar'
  ],
  MapCodes.LD: ['Lakshadweep'],
  MapCodes.NL: [
    'Wokha',
    'Kohima',
    'Phek',
    'Kiphire',
    'Longleng',
    'Peren',
    'Tuensang',
    'Mon',
    'Zunheboto',
    'Dimapur',
    'Mokokchung'
  ],
  MapCodes.LA: ['Leh', 'Kargil'],
  MapCodes.PY: ['Karaikal', 'Puducherry', 'Yanam', 'Mahe'],
  MapCodes.TR: [
    'West Tripura',
    'South Tripura',
    'Unokoti',
    'Gomati',
    'North Tripura',
    'Khowai',
    'Sipahijala',
    'Dhalai'
  ],
  MapCodes.TN: [
    'Tiruppur',
    'Ranipet',
    'Ramanathapuram',
    'Krishnagiri',
    'Karur',
    'Coimbatore',
    'Chennai',
    'Erode',
    'Nilgiris',
    'Chengalpattu',
    'Viluppuram',
    'Tiruvannamalai',
    'Nagapattinam',
    'Tenkasi',
    'Namakkal',
    'Theni',
    'Kanyakumari',
    'Dharmapuri',
    'Thoothukkudi',
    'Perambalur',
    'Tirupathur',
    'Cuddalore',
    'Vellore',
    'Kancheepuram',
    'Thiruvallur',
    'Ariyalur',
    'Dindigul',
    'Madurai',
    'Tirunelveli',
    'Sivaganga',
    'Pudukkottai',
    'Thiruvarur',
    'Tiruchirappalli',
    'Virudhunagar',
    'Salem',
    'Thanjavur',
    'Kallakurichi'
  ],
  MapCodes.TG: [
    'Sangareddy',
    'Khammam',
    'Nalgonda',
    'Nagarkurnool',
    'Yadadri Bhuvanagiri',
    'Warangal Urban',
    'Jayashankar Bhupalapally',
    'Komaram Bheem',
    'Siddipet',
    'Mahabubnagar',
    'Medchal Malkajgiri',
    'Mulugu',
    'Adilabad',
    'Jangaon',
    'Nirmal',
    'Jagtial',
    'Bhadradri Kothagudem',
    'Narayanpet',
    'Medak',
    'Peddapalli',
    'Kamareddy',
    'Rajanna Sircilla',
    'Wanaparthy',
    'Jogulamba Gadwal',
    'Karimnagar',
    'Suryapet',
    'Vikarabad',
    'Hyderabad',
    'Mahabubabad',
    'Nizamabad',
    'Warangal Rural',
    'Ranga Reddy',
    'Mancherial'
  ],
  MapCodes.RJ: [
    'Jaipur',
    'Dausa',
    'Dholpur',
    'Jalore',
    'Bhilwara',
    'Barmer',
    'Jaisalmer',
    'Sirohi',
    'Dungarpur',
    'Udaipur',
    'Alwar',
    'Rajsamand',
    'Pali',
    'Jodhpur',
    'Sikar',
    'Pratapgarh',
    'Ganganagar',
    'Bundi',
    'Nagaur',
    'Jhunjhunu',
    'Baran',
    'Karauli',
    'Chittorgarh',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Jhalawar',
    'Banswara',
    'Churu',
    'Tonk',
    'Hanumangarh',
    'Bharatpur',
    'Sawai Madhopur'
  ],
  MapCodes.CH: ['Chandigarh'],
  MapCodes.AN: ['North and Middle Andaman', 'South Andaman', 'Nicobars'],
  MapCodes.AP: [
    'Krishna',
    'Y.S.R. Kadapa',
    'West Godavari',
    'Kurnool',
    'S.P.S. Nellore',
    'Chittoor',
    'East Godavari',
    'Prakasam',
    'Vizianagaram',
    'Visakhapatnam',
    'Guntur',
    'Srikakulam',
    'Anantapur'
  ],
  MapCodes.AS: [
    'Nalbari',
    'Dhemaji',
    'Morigaon',
    'Nagaon',
    'Sonitpur',
    'Majuli',
    'Baksa',
    'Kokrajhar',
    'Dibrugarh',
    'Kamrup Metropolitan',
    'Kamrup',
    'Jorhat',
    'Darrang',
    'Tinsukia',
    'Dhubri',
    'Charaideo',
    'Biswanath',
    'Hojai',
    'Golaghat',
    'Chirang',
    'Sivasagar',
    'Barpeta',
    'Karbi Anglong',
    'Karimganj',
    'West Karbi Anglong',
    'Hailakandi',
    'Udalguri',
    'Goalpara',
    'Cachar',
    'Bongaigaon',
    'Dima Hasao',
    'South Salmara Mankachar',
    'Lakhimpur'
  ],
  MapCodes.AR: [
    'Namsai',
    'Changlang',
    'Kra Daadi',
    'Longding',
    'Kamle',
    'Upper Dibang Valley',
    'Kurung Kumey',
    'Anjaw',
    'East Siang',
    'Pakke Kessang',
    'Lower Subansiri',
    'Upper Subansiri',
    'Upper Siang',
    'Lower Dibang Valley',
    'Lepa Rada',
    'Lower Siang',
    'West Kameng',
    'Papum Pare',
    'Tawang',
    'Tirap',
    'East Kameng',
    'Lohit',
    'Shi Yomi',
    'Siang',
    'West Siang'
  ],
  MapCodes.GA: ['South Goa', 'North Goa'],
  MapCodes.GJ: [
    'Devbhumi Dwarka',
    'Botad',
    'Bhavnagar',
    'Vadodara',
    'Dang',
    'Jamnagar',
    'Junagadh',
    'Tapi',
    'Navsari',
    'Rajkot',
    'Dahod',
    'Gir Somnath',
    'Porbandar',
    'Panchmahal',
    'Morbi',
    'Ahmedabad',
    'Kheda',
    'Banaskantha',
    'Aravalli',
    'Mahisagar',
    'Amreli',
    'Surat',
    'Bharuch',
    'Sabarkantha',
    'Kutch',
    'Valsad',
    'Surendranagar',
    'Chhota Udaipur',
    'Anand',
    'Mehsana',
    'Patan',
    'Gandhinagar',
    'Narmada'
  ],
  MapCodes.CT: [
    'Mahasamund',
    'Dakshin Bastar Dantewada',
    'Bastar',
    'Narayanpur',
    'Raigarh',
    'Rajnandgaon',
    'Korba',
    'Gariaband',
    'Bametara',
    'Baloda Bazar',
    'Dhamtari',
    'Jashpur',
    'Janjgir Champa',
    'Kabeerdham',
    'Bijapur',
    'Surguja',
    'Balod',
    'Balrampur',
    'Bilaspur',
    'Raipur',
    'Surajpur',
    'Sukma',
    'Kondagaon',
    'Durg',
    'Koriya',
    'Mungeli',
    'Uttar Bastar Kanker'
  ],
  MapCodes.KA: [
    'Haveri',
    'Yadgir',
    'Kalaburagi',
    'Raichur',
    'Kodagu',
    'Bengaluru Urban',
    'Chitradurga',
    'Dakshina Kannada',
    'Uttara Kannada',
    'Udupi',
    'Chikkamagaluru',
    'Mandya',
    'Ballari',
    'Dharwad',
    'Ramanagara',
    'Chikkaballapura',
    'Bengaluru Rural',
    'Bagalkote',
    'Hassan',
    'Tumakuru',
    'Shivamogga',
    'Bidar',
    'Koppal',
    'Vijayapura',
    'Davanagere',
    'Belagavi',
    'Kolar',
    'Chamarajanagara',
    'Gadag',
    'Mysuru'
  ],
  MapCodes.ML: [
    'South West Garo Hills',
    'West Garo Hills',
    'South West Khasi Hills',
    'East Khasi Hills',
    'North Garo Hills',
    'South Garo Hills',
    'West Khasi Hills',
    'East Garo Hills',
    'West Jaintia Hills',
    'East Jaintia Hills',
    'Ribhoi'
  ],
  MapCodes.MN: [
    'Imphal West',
    'Kamjong',
    'Senapati',
    'Tamenglong',
    'Noney',
    'Imphal East',
    'Kangpokpi',
    'Thoubal',
    'Jiribam',
    'Ukhrul',
    'Chandel',
    'Kakching',
    'Bishnupur',
    'Pherzawl',
    'Churachandpur',
    'Tengnoupal'
  ],
  MapCodes.UP: [
    'Chitrakoot',
    'Banda',
    'Firozabad',
    'Farrukhabad',
    'Sitapur',
    'Varanasi',
    'Sant Kabir Nagar',
    'Kaushambi',
    'Budaun',
    'Prayagraj',
    'Kasganj',
    'Shrawasti',
    'Pratapgarh',
    'Baghpat',
    'Chandauli',
    'Pilibhit',
    'Bareilly',
    'Kannauj',
    'Etah',
    'Lakhimpur Kheri',
    'Bahraich',
    'Shahjahanpur',
    'Barabanki',
    'Kanpur Dehat',
    'Mau',
    'Maharajganj',
    'Amethi',
    'Lalitpur',
    'Rampur',
    'Mathura',
    'Unnao',
    'Sonbhadra',
    'Basti',
    'Azamgarh',
    'Lucknow',
    'Sultanpur',
    'Auraiya',
    'Hathras',
    'Gonda',
    'Hardoi',
    'Mahoba',
    'Fatehpur',
    'Muzaffarnagar',
    'Bijnor',
    'Mainpuri',
    'Amroha',
    'Balrampur',
    'Moradabad',
    'Meerut',
    'Bhadohi',
    'Rae Bareli',
    'Shamli',
    'Mirzapur',
    'Hapur',
    'Hamirpur',
    'Jalaun',
    'Siddharthnagar',
    'Kushinagar',
    'Saharanpur',
    'Gorakhpur',
    'Jaunpur',
    'Ghaziabad',
    'Ayodhya',
    'Gautam Buddha Nagar',
    'Deoria',
    'Sambhal',
    'Etawah',
    'Ballia',
    'Aligarh',
    'Ambedkar Nagar',
    'Bulandshahr',
    'Kanpur Nagar',
    'Jhansi',
    'Ghazipur',
    'Agra'
  ],
  MapCodes.KL: [
    'Ernakulam',
    'Palakkad',
    'Malappuram',
    'Kozhikode',
    'Alappuzha',
    'Wayanad',
    'Kottayam',
    'Pathanamthitta',
    'Idukki',
    'Kollam',
    'Thrissur',
    'Thiruvananthapuram',
    'Kasaragod',
    'Kannur'
  ],
  MapCodes.SK: ['South Sikkim', 'East Sikkim', 'West Sikkim', 'North Sikkim'],
  MapCodes.MP: [
    'Dindori',
    'Umaria',
    'Sheopur',
    'Vidisha',
    'Khargone',
    'Sehore',
    'Datia',
    'Guna',
    'Sidhi',
    'Dhar',
    'Agar Malwa',
    'Bhopal',
    'Mandsaur',
    'Damoh',
    'Rajgarh',
    'Indore',
    'Satna',
    'Hoshangabad',
    'Jabalpur',
    'Shivpuri',
    'Seoni',
    'Sagar',
    'Bhind',
    'Tikamgarh',
    'Panna',
    'Khandwa',
    'Neemuch',
    'Burhanpur',
    'Katni',
    'Jhabua',
    'Niwari',
    'Gwalior',
    'Rewa',
    'Shajapur',
    'Singrauli',
    'Shahdol',
    'Mandla',
    'Dewas',
    'Morena',
    'Betul',
    'Barwani',
    'Chhatarpur',
    'Chhindwara',
    'Balaghat',
    'Raisen',
    'Harda',
    'Ashoknagar',
    'Anuppur',
    'Ujjain',
    'Narsinghpur',
    'Alirajpur',
    'Ratlam'
  ],
  MapCodes.UT: [
    'Bageshwar',
    'Rudraprayag',
    'Pithoragarh',
    'Uttarkashi',
    'Haridwar',
    'Dehradun',
    'Udham Singh Nagar',
    'Nainital',
    'Almora',
    'Champawat',
    'Chamoli',
    'Pauri Garhwal',
    'Tehri Garhwal'
  ],
  MapCodes.OR: [
    'Khordha',
    'Subarnapur',
    'Deogarh',
    'Bhadrak',
    'Koraput',
    'Ganjam',
    'Puri',
    'Dhenkanal',
    'Nabarangapur',
    'Gajapati',
    'Kendrapara',
    'Kendujhar',
    'Rayagada',
    'Mayurbhanj',
    'Malkangiri',
    'Boudh',
    'Jajpur',
    'Cuttack',
    'Balasore',
    'Angul',
    'Nuapada',
    'Nayagarh',
    'Bargarh',
    'Jharsuguda',
    'Balangir',
    'Kalahandi',
    'Jagatsinghpur',
    'Sambalpur',
    'Kandhamal',
    'Sundargarh'
  ],
  MapCodes.MZ: [
    'Kolasib',
    'Hnahthial',
    'Saiha',
    'Khawzawl',
    'Mamit',
    'Champhai',
    'Lawngtlai',
    'Aizawl',
    'Lunglei',
    'Serchhip'
  ]
};

const List<String> DISTRICT_SUGGESTIONS = [
  'Madurai',
  'Ganjam',
  'Alappuzha',
  'Mumbai',
  'Chennai',
];

const List<String> STATE_SUGGESTIONS = [
  'Andhra Pradesh',
  'Karnataka',
  'Gujarat',
  'West Bengal',
  'Ladakh',
];
